"""foreign key2

Revision ID: 520876cbfaf3
Revises: ffcd333432f3
Create Date: 2022-03-15 15:40:10.392829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520876cbfaf3'
down_revision = 'ffcd333432f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    # ### end Alembic commands ###
