"""session foreignkey

Revision ID: b8a60f9660f5
Revises: 1a7bccb9cbf5
Create Date: 2022-03-17 10:20:40.689197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a60f9660f5'
down_revision = '1a7bccb9cbf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'session', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    # ### end Alembic commands ###
