"""change user field

Revision ID: 265402cbfeb8
Revises: 1e3dba2423a7
Create Date: 2022-03-04 13:40:56.496166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '265402cbfeb8'
down_revision = '1e3dba2423a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.drop_constraint('users_first_name_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['fullname'])
    op.drop_column('users', 'registration_date')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'lastname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('registration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_first_name_key', 'users', ['first_name'])
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###
