version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8500:80
    depends_on:
      - backend


  postgres:
      image: postgres:12
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - '8501:5432'
      volumes:
        - ./data:/var/lib/postgresql/data:cached

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python main.py
    tty: true
    ports:
      - 8502:8080
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://postgres:postgresd@postgres:8501/postgres'
    depends_on:
      - "postgres"
