"""foreign key

Revision ID: ffcd333432f3
Revises: 3f9517ed7161
Create Date: 2022-03-15 15:36:57.547155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffcd333432f3'
down_revision = '3f9517ed7161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['fullname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('posts', 'user_id')
    # ### end Alembic commands ###
